CLUBS = [
        "MyTeam", "Boavista FC", "Fenerbahçe SK", "Botafogo", "Vitesse", "Eintracht Frankfurt", "Montpellier HSC",
        "Minnesota United FC", "Kawasaki Frontale", "DSC Arminia Bielefeld", "Aarhus GF", "Ajax", "Crystal Palace",
        "Dinamo Zagreb", "Valencia CF", "US Cremonese", "Heracles Almelo", "CD Everton de Viña del Mar",
        "Club Atlético Lanús", "FK Bodø/Glimt", "RCD Mallorca", "Shrewsbury", "Columbus Crew SC", "Shamrock Rovers",
        "Arka Gdynia", "Dundalk", "Real Salt Lake", "Middlesbrough", "Manchester City", "BB Erzurumspor",
        "Vålerenga Fotball", "Málaga CF", "Chicago Fire", "KAS Eupen", "Vélez Sarsfield", "Red Star FC",
        "SV Werder Bremen", "Stevenage", "Incheon United FC", "Nagoya Grampus", "Wisła Płock", "Odds BK",
        "Accrington Stanley", "Universidad Católica", "AIK", "Hamburger SV", "Crotone", "AS Nancy Lorraine",
        "ESTAC Troyes", "Arsenal", "Henan Jianye FC", "Pohang Steelers", "Kilmarnock", "Genoa", "Puebla FC",
        "Boyacá Chicó FC", "Molde FK", "Viktoria Plzeň", "Al Shabab", "Santos", "Club América", "AZ Alkmaar",
        "Southampton", "Vissel Kobe", "SC Paderborn 07", "Club Necaxa", "Grasshopper Club Zürich", "Olympiacos CFP",
        "Tianjin TEDA FC", "Fiorentina", "Chelsea", "Lech Poznań", "Bournemouth", "FC Nantes", "Aston Villa",
        "Feyenoord", "Birmingham City", "FC Admira Wacker Mödling", "PAOK", "Brentford", "Gangwon FC",
        "Akhisar Belediyespor", "Stade Rennais FC", "Willem II", "Swansea City", "Getafe CF",
        "América FC (Minas Gerais)", "New York Red Bulls", "SC Heerenveen", "FK Austria Wien", "VfL Osnabrück",
        "Notts County", "Shakhtar Donetsk", "Guangzhou Evergrande Taobao FC", "Kaizer Chiefs", "Paraná",
        "Deportes Tolima", "Forest Green Rovers", "Coventry City", "Sivasspor", "Derry City", "SD Eibar", "Port Vale",
        "Beijing Renhe FC", "Vancouver Whitecaps FC", "San Martin de Tucumán", "Barnsley", "BK Häcken",
        "Medipol Başakşehir FK", "SK Rapid Wien", "Monarcas Morelia", "Portsmouth", "1. FC Nürnberg",
        "Milton Keynes Dons", "Shonan Bellmare", "Zagłębie Sosnowiec", "AFC Wimbledon", "1. FC Heidenheim 1846",
        "Torino", "Vitória", "Rayo Vallecano", "SV Mattersburg", "Sporting CP", "VfB Stuttgart", "Ascoli", "Pachuca",
        "Deportes Iquique", "Cosenza", "Cittadella", "Aalborg BK", "Miedź Legnica", "Deportivo Cali", "FC Metz",
        "América de Cali", "FC Carl Zeiss Jena", "Club Brugge KV", "Bologna", "FC Dallas", "FC Energie Cottbus",
        "Melbourne City FC", "Levante UD", "TSG 1899 Hoffenheim", "Kasimpaşa SK", "UD Almería", "SCR Altach",
        "Curicó Unido", "Leicester City", "Al Fayha", "Randers FC", "Trelleborgs FF", "Yeovil Town", "Watford",
        "Millonarios FC", "Ettifaq FC", "Wolfsberger AC", "US Orléans Loiret Football", "Newcastle Jets", "Motherwell",
        "Atlético Tucumán", "Gimnasia y Esgrima La Plata", "SK Brann", "Kashima Antlers", "Sevilla FC",
        "RC Strasbourg Alsace", "FC Emmen", "KAA Gent", "Malmö FF", "Stade Brestois 29", "Guangzhou R&F; FC",
        "CD Palestino", "La Berrichonne de Châteauroux", "Beijing Sinobo Guoan FC", "Djurgårdens IF", "FC Lugano",
        "Manchester United", "Rotherham United", "Parma", "San Lorenzo de Almagro", "Cheltenham Town", "FC Luzern",
        "Galatasaray SK", "Milan", "IFK Norrköping", "Itagüí Leones FC", "Albacete BP", "Luton Town", "Grêmio",
        "Rionegro Águilas", "Gimnàstic de Tarragona", "Vejle Boldklub", "Gamba Osaka", "Rochdale",
        "Club Atlético Banfield", "Paris Saint-Germain", "Leeds United", "Kristiansund BK", "Club Tijuana",
        "Ceará Sporting Club", "Al Qadisiyah", "Oldham Athletic", "Crawley Town"

    ]