# Generated by Django 2.2.1 on 2019-06-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190611_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
