# Generated by Django 2.2.1 on 2019-06-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190612_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='creater',
            new_name='creator',
        ),
    ]
